export const genresOptions = [ { key: '1', value: 'Rock', text: 'Rock' }, 
                                { key: '2', value: 'Pop', text: 'Pop' },
                                { key: '3', value: 'Punk', text: 'Punk' },
                                { key: '4', value: 'Metal', text: 'Metal' },
                                { key: '5', value: 'Rap', text: 'Rap' },
                                { key: '6', value: 'Hip-Hop', text: 'Hip-Hop' },
                                { key: '7', value: 'Country', text: 'Country' },
                                { key: '8', value: 'Jazz', text: 'Jazz' },
                                { key: '9', value: 'Rock alternatywny', text: 'Rock alternatywny' },
                                { key: '10', value: 'Rock klasyczny', text: 'Rock klasyczny' },
                                { key: '11', value: 'Disco polo', text: 'Disco polo' },
                                { key: '12', value: 'Heavy Metal', text: 'Heavy Metal' },
                                { key: '13', value: 'Klasyka', text: 'Klasyka' },
                                { key: '14', value: 'Opera', text: 'Opera' },
                                { key: '15', value: 'Reggae', text: 'Reggae' },
                                { key: '16', value: 'Soul', text: 'Soul' } ];

export const yearsOptions = [ { key: '1', value: '2019', text: '2019' },
                       { key: '2', value: '2018', text: '2018' },
                       { key: '3', value: '2017', text: '2017' },
                       { key: '4', value: '2016', text: '2016' }, 
                       { key: '5', value: '2015', text: '2015' },
                       { key: '6', value: '2014', text: '2014' },
                       { key: '7', value: '2013', text: '2013' },
                       { key: '8', value: '2012', text: '2012' },
                       { key: '9', value: '2011', text: '2011' },
                       { key: '10', value: '2010', text: '2010' },
                       { key: '11', value: '2009', text: '2009' },
                       { key: '12', value: '2008', text: '2008' },
                       { key: '13', value: '2007', text: '2007' },
                       { key: '14', value: '2006', text: '2006' },
                       { key: '15', value: '1990', text: '1990' },
                       { key: '16', value: '1989', text: '1989' },
                       { key: '17', value: '1988', text: '1988' },
                       { key: '18', value: '1987', text: '1987' },
                       { key: '19', value: '1986', text: '1986' },
                       { key: '20', value: '1985', text: '1985' },
                       { key: '21', value: '1984', text: '1984' },
                       { key: '22', value: '1983', text: '1983' },
                       { key: '23', value: '1982', text: '1982' },
                       { key: '24', value: '1981', text: '1981' },
                       { key: '25', value: '1980', text: '1980' },
                       { key: '26', value: '1979', text: '1979' },
                       { key: '27', value: '1978', text: '1978' },
                       { key: '28', value: '1977', text: '1977' },
                       { key: '29', value: '1976', text: '1976' } ]

export const sortOptions = [ { key: 1, text: 'oceny rosnąco',value: 1 },
                             { key: 2, text: 'oceny malejąco',value: 2 },
                             { key: 3, text: 'liczba głosów rosnąca', value: 3 },
                             { key: 4, text: 'liczba głosów malejąco', value: 4 },
                             { key: 5, text: 'od najstarszych',value: 5 },
                             { key: 6, text: 'od najnowszych', value: 6 }]

                        